# Generated by Django 5.0.6 on 2024-11-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_remove_userprofile_password_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
