# Generated by Django 5.0.6 on 2024-11-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0006_batchyear_studentbatch_studentdocument_studentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfile',
            name='batch',
        ),
        migrations.DeleteModel(
            name='BatchYear',
        ),
        migrations.DeleteModel(
            name='StudentFile',
        ),
    ]
