# Generated by Django 5.0.6 on 2024-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
