# Generated by Django 3.2.16 on 2024-11-16 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_academicyear_delete_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adminpage.academicyear'),
        ),
    ]
