# Generated by Django 3.2.16 on 2024-11-24 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_alter_studentdocument_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_in', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('academic_year_in', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='performance_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adminpage.studentperformance')),
            ],
        ),
    ]
