# Generated by Django 3.2.16 on 2024-11-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_achievement_achievementdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementdocument',
            name='achievement',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='AchievementDocument',
        ),
    ]
