# Generated by Django 5.0.6 on 2024-11-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0020_alter_document_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancechart',
            name='avg_sgpa_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancechart',
            name='avg_sgpa_vi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='avg_sgpa_iii',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='avg_sgpa_iv',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
