# Generated by Django 5.0.6 on 2024-11-27 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0022_performancechart_academic_performance_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancechart',
            name='academic_performance_index',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_i',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_ii',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_iii',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_iv',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_v',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_vi',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_vii',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='avg_sgpa_viii',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='mean_percentage_successful',
        ),
        migrations.RemoveField(
            model_name='performancechart',
            name='total_successful_students',
        ),
        migrations.AddField(
            model_name='performancechart',
            name='semester_averages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='avg_cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='detained_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='performance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_chart', to='adminpage.studentperformance'),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='total_cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancechart',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
    ]
