# Generated by Django 5.0.6 on 2024-12-02 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0023_remove_performancechart_academic_performance_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassoutYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('ISE', 'Information Science'), ('ECE', 'Electronics and Communication'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_letter', models.FileField(help_text='Upload offer letter (PDF, JPG, PNG)', upload_to='offer_letters/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('passout_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='adminpage.passoutyear')),
            ],
        ),
    ]
