# Generated by Django 5.0.6 on 2024-12-04 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0024_passoutyear_placementrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passoutyear',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('passout_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_details', to='adminpage.passoutyear')),
            ],
        ),
        migrations.DeleteModel(
            name='PlacementRecord',
        ),
    ]
