# Generated by Django 5.0.6 on 2024-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0025_alter_passoutyear_year_placementdetails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdetails',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
    ]
