# Generated by Django 3.2.16 on 2024-12-11 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0028_alter_higherstudy_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='higherstudydocument',
            name='higher_study',
        ),
        migrations.DeleteModel(
            name='HigherStudy',
        ),
        migrations.DeleteModel(
            name='HigherStudyDocument',
        ),
    ]
