# Generated by Django 3.2.16 on 2024-12-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0031_auto_20241211_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='higher_study_documents/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('higher_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adminpage.higherstudy')),
            ],
        ),
    ]
