# Generated by Django 5.0.6 on 2024-12-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0036_placementdetails_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementdetails',
            name='offer_letter',
        ),
        migrations.RemoveField(
            model_name='placementdetails',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='passoutyear',
            name='year',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='offer_letters/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('placement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='adminpage.placementdetails')),
            ],
        ),
    ]
