# Generated by Django 5.0.6 on 2024-12-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0037_remove_placementdetails_offer_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
