# Generated by Django 5.0.6 on 2024-12-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0039_placementdetails_adminpage_p_name_7039a0_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='placementdetails',
            name='adminpage_p_name_7039a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='placementdetails',
            name='adminpage_p_usn_b81809_idx',
        ),
        migrations.RemoveIndex(
            model_name='placementdetails',
            name='adminpage_p_company_a31b9d_idx',
        ),
        migrations.RemoveIndex(
            model_name='placementdetails',
            name='adminpage_p_passout_0665db_idx',
        ),
        migrations.AddField(
            model_name='performancechart',
            name='max_cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performancechart',
            name='min_cgpa',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='performancechart',
            name='overall_sgpa_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
